timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--build-arg', 'PROJECT_ID=${PROJECT_ID}',
    '-t', '${_CI_REGISTRY_IMAGE}/${PROJECT_ID}/${_CI_REGISTRY_IMAGE_NAME}/${_CONTAINERNAME}:${COMMIT_SHA}', 
    '.'
  ]

# Step 2: Push the Docker image to the registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_CI_REGISTRY_IMAGE}/${PROJECT_ID}/${_CI_REGISTRY_IMAGE_NAME}/${_CONTAINERNAME}:${COMMIT_SHA}']

# Step 3: Deploy the Docker image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', '${_CONTAINERNAME}',
    '--image', '${_CI_REGISTRY_IMAGE}/${PROJECT_ID}/${_CI_REGISTRY_IMAGE_NAME}/${_CONTAINERNAME}:${COMMIT_SHA}',
    '--platform', 'managed',
    '--region', '${_ZONE}',
    '--allow-unauthenticated',
    '--memory', '512Mi',
    '--cpu', '1',
    '--ingress', 'internal-and-cloud-load-balancing',
    '--max-instances', '1',
    '--min-instances', '0',
    '--set-env-vars', 'PROJECT_ID=${PROJECT_ID}',
    '--network', 'projects/${PROJECT_ID}/global/networks/${PROJECT_ID}-vpc',
    '--subnet', 'projects/${PROJECT_ID}/regions/${_ZONE}/subnetworks/${PROJECT_ID}-vpc-subnet',
    '--vpc-egress', 'all-traffic',
    "--service-account", "testing-domanda-get-date-data@${PROJECT_ID}.iam.gserviceaccount.com"
  ]

images:
- '${_CI_REGISTRY_IMAGE}/${PROJECT_ID}/${_CI_REGISTRY_IMAGE_NAME}/${_CONTAINERNAME}:${COMMIT_SHA}'